In [ ]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import roc_auc_score

import pandas as pd

data = pd.read_csv('train.csv', index_col='PassengerId')
y = data.pop('Survived')

data_test = pd.read_csv('test.csv', index_col='PassengerId')

### So far I have *data*: {X_train, y_train, X_test, y_test} or the training set, *y*: {depended variable}, and *data_test*:{Kaggle test set or the real X_test}

### I'm simultaneously preprocessing the datasets X_train, X_test, and data_test.  And then I'm going to train on the full dataset data doing preprocessing all over again on *data* and *data_test*

### So in the beginning all I'm doing is trying to figure out how good the ML algorithm is by using it only on *data:{X_train, y_train, X_test, y_test}, fit_transforming X_train, then transforming on X_test, and then fitting on X_train, y_train, and then predicting on X_test.

In [2]:
data.head()

Pclass                                               Name  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   

                Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
PassengerId                                                                
1              male  22.0      1      0         A/5 21171   7.2500   NaN   
2            female  38.0      1      0          PC 17599  71.2833   C85   
3            female  26.0      0      0  STON/O2. 3101282   7.9250   NaN   
4            female  35.0      1      0            113803  53.1000  C123   
5              male  35.0      0      0            373450   8.0500   NaN   

            Embarked  
PassengerId           
1                  S  
2                  C  
3                  S  
4                  S  
5                  S

In [3]:
data_test.head()

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

              Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
PassengerId                                                       
892          34.5      0      0   330911   7.8292   NaN        Q  
893          47.0      1      0   363272   7.0000   NaN        S  
894          62.0      0      0   240276   9.6875   NaN        Q  
895          27.0      0      0   315154   8.6625   NaN        S  
896          22.0      1      1  3101298  12.2875   NaN        S

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.2, random_state=0)

In [6]:
X_train.shape

(712, 10)

In [7]:
y_train.shape

(712,)

In [8]:
X_test.shape

(179, 10)

In [9]:
y_test.shape

(179,)

In [10]:
X_train.describe()

Pclass         Age       SibSp       Parch       Fare
count  712.000000  571.000000  712.000000  712.000000  712.00000
mean     2.317416   29.745184    0.529494    0.391854   31.86295
std      0.833767   14.619046    1.140842    0.821368   50.13531
min      1.000000    0.670000    0.000000    0.000000    0.00000
25%      2.000000   20.750000    0.000000    0.000000    7.91770
50%      3.000000   29.000000    0.000000    0.000000   14.45625
75%      3.000000   38.000000    1.000000    0.000000   31.27500
max      3.000000   80.000000    8.000000    6.000000  512.32920

In [11]:
X_test.describe()

Pclass         Age       SibSp       Parch        Fare
count  179.000000  143.000000  179.000000  179.000000  179.000000
mean     2.273743   29.515175    0.497207    0.340782   33.561615
std      0.846628   14.199825    0.938408    0.742802   48.008223
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      1.000000   20.000000    0.000000    0.000000    7.972900
50%      3.000000   27.000000    0.000000    0.000000   14.000000
75%      3.000000   39.500000    1.000000    0.000000   30.500000
max      3.000000   64.000000    5.000000    5.000000  263.000000

In [12]:
# Impute 'Age' with mean
X_train['Age'].fillna(X_train.Age.mean(), inplace=True)


# Confirm with dataset
X_train.describe()

/Users/Alexander/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3660: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


Pclass         Age       SibSp       Parch       Fare
count  712.000000  712.000000  712.000000  712.000000  712.00000
mean     2.317416   29.745184    0.529494    0.391854   31.86295
std      0.833767   13.089458    1.140842    0.821368   50.13531
min      1.000000    0.670000    0.000000    0.000000    0.00000
25%      2.000000   22.000000    0.000000    0.000000    7.91770
50%      3.000000   29.745184    0.000000    0.000000   14.45625
75%      3.000000   35.000000    1.000000    0.000000   31.27500
max      3.000000   80.000000    8.000000    6.000000  512.32920

In [13]:
X_test['Age'].fillna(X_train.Age.mean(), inplace=True)

X_test.describe()

/Users/Alexander/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3660: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


Pclass         Age       SibSp       Parch        Fare
count  179.000000  179.000000  179.000000  179.000000  179.000000
mean     2.273743   29.561434    0.497207    0.340782   33.561615
std      0.846628   12.683196    0.938408    0.742802   48.008223
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      1.000000   22.000000    0.000000    0.000000    7.972900
50%      3.000000   29.745184    0.000000    0.000000   14.000000
75%      3.000000   34.000000    1.000000    0.000000   30.500000
max      3.000000   64.000000    5.000000    5.000000  263.000000

In [14]:
X_train_numeric_variables = list(X_train.dtypes[X_train.dtypes != "object"].index)
X_train[X_train_numeric_variables].head()

Pclass        Age  SibSp  Parch     Fare
PassengerId                                          
141               3  29.745184      0      2  15.2458
440               2  31.000000      0      0  10.5000
818               2  31.000000      1      1  37.0042
379               3  20.000000      0      0   4.0125
492               3  21.000000      0      0   7.2500

In [15]:
X_test_numeric_variables = list(X_test.dtypes[X_test.dtypes != "object"].index)
X_test[X_test_numeric_variables].head()

Pclass        Age  SibSp  Parch      Fare
PassengerId                                           
496               3  29.745184      0      0   14.4583
649               3  29.745184      0      0    7.5500
279               3   7.000000      4      1   29.1250
32                1  29.745184      1      0  146.5208
256               3  29.000000      0      2   15.2458

In [16]:
model = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=42)

model.fit(X_train[X_train_numeric_variables], y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=42, verbose=0, warm_start=False)

In [17]:
model.oob_score_

0.6783707865168539

In [18]:
X_train.head()

Pclass                                    Name     Sex  \
PassengerId                                                           
141               3           Boulos, Mrs. Joseph (Sultana)  female   
440               2  Kvillner, Mr. Johan Henrik Johannesson    male   
818               2                      Mallet, Mr. Albert    male   
379               3                     Betros, Mr. Tannous    male   
492               3                     Windelov, Mr. Einar    male   

                   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                                     
141          29.745184      0      2              2678  15.2458   NaN        C  
440          31.000000      0      0        C.A. 18723  10.5000   NaN        S  
818          31.000000      1      1   S.C./PARIS 2079  37.0042   NaN        C  
379          20.000000      0      0              2648   4.0125   NaN        C  
492          21.000000      0      0  SOTON/OQ 3101317   7.2500   NaN        S

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(model, X_train[X_train_numeric_variables], y_train, cv=5, scoring="accuracy")

array([ 0.67832168,  0.69230769,  0.72727273,  0.69014085,  0.70212766])

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(X_train[X_train_numeric_variables])

array([[ 0.81925059,  0.        , -0.46445234,  1.95926403, -0.33167904],
       [-0.38096838,  0.09593203, -0.46445234, -0.47741019, -0.42640542],
       [-0.38096838,  0.09593203,  0.41270964,  0.74092692,  0.10261958],
       ..., 
       [ 0.81925059,  0.        , -0.46445234, -0.47741019, -0.48162887],
       [ 0.81925059,  0.47818735,  0.41270964, -0.47741019, -0.28868112],
       [-0.38096838,  2.31301288,  0.41270964,  0.74092692,  0.14245584]])

In [22]:
from sklearn.preprocessing import StandardScaler

scaler.transform(X_test[X_test_numeric_variables])

array([[  8.19250590e-01,  -2.71608741e-16,  -4.64452339e-01,
         -4.77410187e-01,  -3.47397578e-01],
       [  8.19250590e-01,  -2.71608741e-16,  -4.64452339e-01,
         -4.77410187e-01,  -4.85287550e-01],
       [  8.19250590e-01,  -1.73889351e+00,   3.04419557e+00,
          7.40926921e-01,  -5.46495998e-02],
       [ -1.58118735e+00,  -2.71608741e-16,   4.12709638e-01,
         -4.77410187e-01,   2.28857574e+00],
       [  8.19250590e-01,  -5.69701011e-02,  -4.64452339e-01,
          1.95926403e+00,  -3.31679043e-01],
       [ -1.58118735e+00,  -2.71608741e-16,  -4.64452339e-01,
         -4.77410187e-01,  -2.72045392e-02],
       [ -1.58118735e+00,   7.83991602e-01,  -4.64452339e-01,
         -4.77410187e-01,   2.42713238e+00],
       [ -1.58118735e+00,   9.59320268e-02,  -4.64452339e-01,
          1.95926403e+00,   2.65476071e+00],
       [ -1.58118735e+00,  -3.62774357e-01,   4.12709638e-01,
         -4.77410187e-01,   1.18195896e+00],
       [  8.19250590e-01,  -2.7160874

In [23]:
model = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=42)

model.fit(X_train[X_train_numeric_variables], y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=42, verbose=0, warm_start=False)

In [24]:
cross_val_score(model, X_train[X_train_numeric_variables], y_train, cv=5, scoring="accuracy")

array([ 0.67832168,  0.69230769,  0.72727273,  0.69014085,  0.70212766])

In [25]:
cross_val_score(model, X_test[X_test_numeric_variables], y_test, cv=5, scoring="accuracy")

array([ 0.72222222,  0.61111111,  0.75      ,  0.69444444,  0.74285714])

In [26]:
pred = model.predict(X_test[X_test_numeric_variables])

In [27]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)

In [28]:
print("accuracy: ", acc)

accuracy:  0.715083798883


### This would be my benchmark to compare against all other algorithms

In [29]:
X_train.drop(["Name", "Ticket"], axis=1, inplace=True)

/Users/Alexander/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [30]:
X_test.drop(["Name", "Ticket"], axis=1, inplace=True)

/Users/Alexander/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [31]:
# here is a simple function to show descriptive stats on the categorical variables
def describe_categorical(data):
    """
    Just like .describe(), but returns the results for categorical variables only
    """
    from IPython.display import display, HTML
    display(HTML(data[data.columns[data.dtypes == "object"]].describe().to_html()))

In [32]:
describe_categorical(X_train)

In [33]:
def clean_cabin(X_train):
    try:
        return X_train[0]
    except TypeError:
        return "None"
X_train["Cabin"]  = X_train.Cabin.apply(clean_cabin)

/Users/Alexander/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [34]:
describe_categorical(X_train)

In [35]:
X_train.head(100)

Pclass     Sex        Age  SibSp  Parch      Fare Cabin Embarked
PassengerId                                                                  
141               3  female  29.745184      0      2   15.2458  None        C
440               2    male  31.000000      0      0   10.5000  None        S
818               2    male  31.000000      1      1   37.0042  None        C
379               3    male  20.000000      0      0    4.0125  None        C
492               3    male  21.000000      0      0    7.2500  None        S
332               1    male  45.500000      0      0   28.5000     C        S
589               3    male  22.000000      0      0    8.0500  None        S
359               3  female  29.745184      0      0    7.8792  None        Q
675               2    male  29.745184      0      0    0.0000  None        S
163               3    male  26.000000      0      0    7.7750  None        S
581               2  female  25.000000      1      1   30.0000  None        S
403               3  female  21.000000      1      0    9.8250  None        S
672               1    male  31.000000      1      0   52.0000     B        S
876               3  female  15.000000      0      0    7.2250  None        C
728               3  female  29.745184      0      0    7.7375  None        Q
429               3    male  29.745184      0      0    7.7500  None        Q
55                1    male  65.000000      0      1   61.9792     B        C
46                3    male  29.745184      0      0    8.0500  None        S
173               3  female   1.000000      1      1   11.1333  None        S
448               1    male  34.000000      0      0   26.5500  None        S
598               3    male  49.000000      0      0    0.0000  None        S
205               3    male  18.000000      0      0    8.0500  None        S
241               3  female  29.745184      1      0   14.4542  None        C
673               2    male  70.000000      0      0   10.5000  None        S
40                3  female  14.000000      1      0   11.2417  None        C
284               3    male  19.000000      0      0    8.0500  None        S
309               2    male  30.000000      1      0   24.0000  None        C
19                3  female  31.000000      1      0   18.0000  None        S
770               3    male  32.000000      0      0    8.3625  None        S
157               3  female  16.000000      0      0    7.7333  None        Q
...             ...     ...        ...    ...    ...       ...   ...      ...
824               3  female  27.000000      0      1   12.4750     E        S
522               3    male  22.000000      0      0    7.8958  None        S
334               3    male  16.000000      2      0   18.0000  None        S
699               1    male  49.000000      1      1  110.8833     C        C
482               2    male  29.745184      0      0    0.0000  None        S
72                3  female  16.000000      5      2   46.9000  None        S
50                3  female  18.000000      1      0   17.8000  None        S
574               3  female  29.745184      0      0    7.7500  None        Q
339               3    male  45.000000      0      0    8.0500  None        S
262               3    male   3.000000      4      2   31.3875  None        S
117               3    male  70.500000      0      0    7.7500  None        Q
77                3    male  29.745184      0      0    7.8958  None        S
49                3    male  29.745184      2      0   21.6792  None        C
844               3    male  34.500000      0      0    6.4375  None        C
264               1    male  40.000000      0      0    0.0000     B        S
719               3    male  29.745184      0      0   15.5000  None        Q
621               3    male  27.000000      1      0   14.4542  None        C
787               3  female  18.000000      0      0    7.4958  None        S
65                1    male  29.745

In [36]:
def clean_cabin(X_test):
    try:
        return X_test[0]
    except TypeError:
        return "None"
X_test["Cabin"] = X_test.Cabin.apply(clean_cabin)

/Users/Alexander/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [37]:
X_test.head()

Pclass     Sex        Age  SibSp  Parch      Fare Cabin Embarked
PassengerId                                                                  
496               3    male  29.745184      0      0   14.4583  None        C
649               3    male  29.745184      0      0    7.5500  None        S
279               3    male   7.000000      4      1   29.1250  None        Q
32                1  female  29.745184      1      0  146.5208     B        C
256               3  female  29.000000      0      2   15.2458  None        C

In [38]:
categorical_variables = ['Sex', 'Cabin', 'Embarked']

for variable in categorical_variables:
    # Fill missing data with the word "Missing"
    X_train[variable].fillna("Missing", inplace=True)
    # Create array of dummies
    dummies = pd.get_dummies(X_train[variable], prefix=variable)
    # Update X to include dummies and drop the main variable
    # here I think axis=1 for pd.concat because the dummies are part of X DataFrame
    X_train = pd.concat([X_train, dummies], axis=1)
    X_train.drop([variable], axis=1, inplace=True)

/Users/Alexander/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3660: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [39]:
X_train.head()

Pclass        Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
PassengerId                                                                   
141               3  29.745184      0      2  15.2458           1         0   
440               2  31.000000      0      0  10.5000           0         1   
818               2  31.000000      1      1  37.0042           0         1   
379               3  20.000000      0      0   4.0125           0         1   
492               3  21.000000      0      0   7.2500           0         1   

             Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  Cabin_G  \
PassengerId                                                                  
141                0        0        0        0        0        0        0   
440                0        0        0        0        0        0        0   
818                0        0        0        0        0        0        0   
379                0        0        0        0        0        0        0   
492                0        0        0        0        0        0        0   

             Cabin_None  Cabin_T  Embarked_C  Embarked_Missing  Embarked_Q  \
PassengerId                                                                  
141                   1        0           1                 0           0   
440                   1        0           0                 0           0   
818                   1        0           1                 0           0   
379                   1        0           1                 0           0   
492                   1        0           0                 0           0   

             Embarked_S  
PassengerId              
141                   0  
440                   1  
818                   0  
379                   0  
492                   1

In [40]:
categorical_variables = ['Sex', 'Cabin', 'Embarked']

for variable in categorical_variables:
    # Fill missing data with the word "Missing"
    X_test[variable].fillna("Missing", inplace=True)
    # Create array of dummies
    dummies = pd.get_dummies(X_test[variable], prefix=variable)
    # Update X to include dummies and drop the main variable
    # here I think axis=1 for pd.concat because the dummies are part of X DataFrame
    X_test = pd.concat([X_test, dummies], axis=1)
    X_test.drop([variable], axis=1, inplace=True)

/Users/Alexander/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3660: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [41]:
X_test.head()

Pclass        Age  SibSp  Parch      Fare  Sex_female  Sex_male  \
PassengerId                                                                    
496               3  29.745184      0      0   14.4583           0         1   
649               3  29.745184      0      0    7.5500           0         1   
279               3   7.000000      4      1   29.1250           0         1   
32                1  29.745184      1      0  146.5208           1         0   
256               3  29.000000      0      2   15.2458           1         0   

             Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_None  \
PassengerId                                                                     
496                0        0        0        0        0        0           1   
649                0        0        0        0        0        0           1   
279                0        0        0        0        0        0           1   
32                 1        0        0        0        0        0           0   
256                0        0        0        0        0        0           1   

             Embarked_C  Embarked_Q  Embarked_S  
PassengerId                                      
496                   1           0           0  
649                   0           0           1  
279                   0           1           0  
32                    1           0           0  
256                   1           0           0

In [42]:
X_train.drop(["Cabin_A", "Cabin_T", "Embarked_Missing"], axis=1, inplace=True)

In [43]:
X_train.head()

Pclass        Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
PassengerId                                                                   
141               3  29.745184      0      2  15.2458           1         0   
440               2  31.000000      0      0  10.5000           0         1   
818               2  31.000000      1      1  37.0042           0         1   
379               3  20.000000      0      0   4.0125           0         1   
492               3  21.000000      0      0   7.2500           0         1   

             Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_None  \
PassengerId                                                                     
141                0        0        0        0        0        0           1   
440                0        0        0        0        0        0           1   
818                0        0        0        0        0        0           1   
379                0        0        0        0        0        0           1   
492                0        0        0        0        0        0           1   

             Embarked_C  Embarked_Q  Embarked_S  
PassengerId                                      
141                   1           0           0  
440                   0           0           1  
818                   1           0           0  
379                   1           0           0  
492                   0           0           1

In [44]:
model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [45]:
cross_val_score(model, X_train, y_train, cv=10, scoring="accuracy")

array([ 0.79166667,  0.79166667,  0.76388889,  0.8028169 ,  0.8028169 ,
        0.8028169 ,  0.8028169 ,  0.77464789,  0.78873239,  0.82857143])

In [46]:
cross_val_score(model, X_test, y_test, cv=10, scoring="accuracy")

array([ 0.88888889,  0.94444444,  0.83333333,  0.72222222,  0.77777778,
        0.83333333,  0.88888889,  0.94444444,  0.77777778,  0.94117647])

In [47]:
pred = model.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)

In [49]:
print("accuracy score: ", acc)

accuracy score:  0.821229050279


### Working on the full dataframe -> *data* and *data_test*

In [50]:
data['Age'].fillna(data.Age.mean(), inplace=True)

data.describe()

Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000
mean     2.308642   29.699118    0.523008    0.381594   32.204208
std      0.836071   13.002015    1.102743    0.806057   49.693429
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   22.000000    0.000000    0.000000    7.910400
50%      3.000000   29.699118    0.000000    0.000000   14.454200
75%      3.000000   35.000000    1.000000    0.000000   31.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200

In [51]:
data_test['Age'].fillna(data.Age.mean(), inplace=True)

data_test.describe()

Pclass         Age       SibSp       Parch        Fare
count  418.000000  418.000000  418.000000  418.000000  417.000000
mean     2.265550   30.154603    0.447368    0.392344   35.627188
std      0.841838   12.636666    0.896760    0.981429   55.907576
min      1.000000    0.170000    0.000000    0.000000    0.000000
25%      1.000000   23.000000    0.000000    0.000000    7.895800
50%      3.000000   29.699118    0.000000    0.000000   14.454200
75%      3.000000   35.750000    1.000000    0.000000   31.500000
max      3.000000   76.000000    8.000000    9.000000  512.329200

In [52]:
data_test['Fare'].fillna(data.Fare.mean(), inplace=True)

data_test.describe()

Pclass         Age       SibSp       Parch        Fare
count  418.000000  418.000000  418.000000  418.000000  418.000000
mean     2.265550   30.154603    0.447368    0.392344   35.619000
std      0.841838   12.636666    0.896760    0.981429   55.840751
min      1.000000    0.170000    0.000000    0.000000    0.000000
25%      1.000000   23.000000    0.000000    0.000000    7.895800
50%      3.000000   29.699118    0.000000    0.000000   14.454200
75%      3.000000   35.750000    1.000000    0.000000   31.500000
max      3.000000   76.000000    8.000000    9.000000  512.329200

In [53]:
data.drop(["Name", "Ticket"], axis=1, inplace=True)
data_test.drop(["Name", "Ticket"], axis=1, inplace=True)

In [54]:
data.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
PassengerId                                                            
1                 3    male  22.0      1      0   7.2500   NaN        S
2                 1  female  38.0      1      0  71.2833   C85        C
3                 3  female  26.0      0      0   7.9250   NaN        S
4                 1  female  35.0      1      0  53.1000  C123        S
5                 3    male  35.0      0      0   8.0500   NaN        S

In [55]:
data_test.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
PassengerId                                                            
892               3    male  34.5      0      0   7.8292   NaN        Q
893               3  female  47.0      1      0   7.0000   NaN        S
894               2    male  62.0      0      0   9.6875   NaN        Q
895               3    male  27.0      0      0   8.6625   NaN        S
896               3  female  22.0      1      1  12.2875   NaN        S

### Something we forgot to do was scale the numerical variables so I'm going to attempt that here

In [56]:
data_num = data.drop(['Sex', 'Cabin', 'Embarked'], axis=1)

In [57]:
data_num.head()

Pclass   Age  SibSp  Parch     Fare
PassengerId                                     
1                 3  22.0      1      0   7.2500
2                 1  38.0      1      0  71.2833
3                 3  26.0      0      0   7.9250
4                 1  35.0      1      0  53.1000
5                 3  35.0      0      0   8.0500

In [58]:
data_test_num = data_test.drop(['Sex', 'Cabin', 'Embarked'], axis=1)

In [59]:
data_test_num.head()

Pclass   Age  SibSp  Parch     Fare
PassengerId                                     
892               3  34.5      0      0   7.8292
893               3  47.0      1      0   7.0000
894               2  62.0      0      0   9.6875
895               3  27.0      0      0   8.6625
896               3  22.0      1      1  12.2875

In [60]:
data.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
PassengerId                                                            
1                 3    male  22.0      1      0   7.2500   NaN        S
2                 1  female  38.0      1      0  71.2833   C85        C
3                 3  female  26.0      0      0   7.9250   NaN        S
4                 1  female  35.0      1      0  53.1000  C123        S
5                 3    male  35.0      0      0   8.0500   NaN        S

### Ignore the above.  

### We're going to do this without having to drop variables and instead just do fit_transforms on just the numerical variables inplace.

In [61]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

data[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']] = scaler.fit_transform(data[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']])

In [62]:
data.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
1            0.827377    male -0.592481  0.432793 -0.473674 -0.502445   NaN   
2           -1.566107  female  0.638789  0.432793 -0.473674  0.786845   C85   
3            0.827377  female -0.284663 -0.474545 -0.473674 -0.488854   NaN   
4           -1.566107  female  0.407926  0.432793 -0.473674  0.420730  C123   
5            0.827377    male  0.407926 -0.474545 -0.473674 -0.486337   NaN   

            Embarked  
PassengerId           
1                  S  
2                  C  
3                  S  
4                  S  
5                  S

In [63]:
data_test[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']] = scaler.transform(data_test[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']])

In [64]:
data_test.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
892          0.827377    male  0.369449 -0.474545 -0.473674 -0.490783   NaN   
893          0.827377  female  1.331378  0.432793 -0.473674 -0.507479   NaN   
894         -0.369365    male  2.485693 -0.474545 -0.473674 -0.453367   NaN   
895          0.827377    male -0.207709 -0.474545 -0.473674 -0.474005   NaN   
896          0.827377  female -0.592481  0.432793  0.767630 -0.401017   NaN   

            Embarked  
PassengerId           
892                Q  
893                S  
894                Q  
895                S  
896                S

### Remember.  You fit_transform on the training set and simply transform on the test set!

### Also, RandomForest, Decision Tree, and Gradient Boosted Models don't care for scaled data.  Only models like SVM and LogisticRegression and other Linear Models and Neural Networks care for scaled data.

In [65]:
#data_test_num = scaler.transform(data_test_num)

In [66]:
#data_test_num

In [67]:
data.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
1            0.827377    male -0.592481  0.432793 -0.473674 -0.502445   NaN   
2           -1.566107  female  0.638789  0.432793 -0.473674  0.786845   C85   
3            0.827377  female -0.284663 -0.474545 -0.473674 -0.488854   NaN   
4           -1.566107  female  0.407926  0.432793 -0.473674  0.420730  C123   
5            0.827377    male  0.407926 -0.474545 -0.473674 -0.486337   NaN   

            Embarked  
PassengerId           
1                  S  
2                  C  
3                  S  
4                  S  
5                  S

In [68]:
data_test.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
892          0.827377    male  0.369449 -0.474545 -0.473674 -0.490783   NaN   
893          0.827377  female  1.331378  0.432793 -0.473674 -0.507479   NaN   
894         -0.369365    male  2.485693 -0.474545 -0.473674 -0.453367   NaN   
895          0.827377    male -0.207709 -0.474545 -0.473674 -0.474005   NaN   
896          0.827377  female -0.592481  0.432793  0.767630 -0.401017   NaN   

            Embarked  
PassengerId           
892                Q  
893                S  
894                Q  
895                S  
896                S

In [69]:
data_test.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
892          0.827377    male  0.369449 -0.474545 -0.473674 -0.490783   NaN   
893          0.827377  female  1.331378  0.432793 -0.473674 -0.507479   NaN   
894         -0.369365    male  2.485693 -0.474545 -0.473674 -0.453367   NaN   
895          0.827377    male -0.207709 -0.474545 -0.473674 -0.474005   NaN   
896          0.827377  female -0.592481  0.432793  0.767630 -0.401017   NaN   

            Embarked  
PassengerId           
892                Q  
893                S  
894                Q  
895                S  
896                S

In [70]:
def clean_cabin(data):
    try:
        return data[0]
    except TypeError:
        return "None"
data["Cabin"]  = data.Cabin.apply(clean_cabin)

In [71]:
data.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
1            0.827377    male -0.592481  0.432793 -0.473674 -0.502445  None   
2           -1.566107  female  0.638789  0.432793 -0.473674  0.786845     C   
3            0.827377  female -0.284663 -0.474545 -0.473674 -0.488854  None   
4           -1.566107  female  0.407926  0.432793 -0.473674  0.420730     C   
5            0.827377    male  0.407926 -0.474545 -0.473674 -0.486337  None   

            Embarked  
PassengerId           
1                  S  
2                  C  
3                  S  
4                  S  
5                  S

In [72]:
def clean_cabin(data_test):
    try:
        return data_test[0]
    except TypeError:
        return "None"
data_test["Cabin"]  = data_test.Cabin.apply(clean_cabin)

In [73]:
data_test.head()

Pclass     Sex       Age     SibSp     Parch      Fare Cabin  \
PassengerId                                                                   
892          0.827377    male  0.369449 -0.474545 -0.473674 -0.490783  None   
893          0.827377  female  1.331378  0.432793 -0.473674 -0.507479  None   
894         -0.369365    male  2.485693 -0.474545 -0.473674 -0.453367  None   
895          0.827377    male -0.207709 -0.474545 -0.473674 -0.474005  None   
896          0.827377  female -0.592481  0.432793  0.767630 -0.401017  None   

            Embarked  
PassengerId           
892                Q  
893                S  
894                Q  
895                S  
896                S

In [74]:
categorical_variables = ['Sex', 'Cabin', 'Embarked']

for variable in categorical_variables:
    # Fill missing data with the word "Missing"
    data[variable].fillna("Missing", inplace=True)
    # Create array of dummies
    dummies = pd.get_dummies(data[variable], prefix=variable)
    # Update X to include dummies and drop the main variable
    # here I think axis=1 for pd.concat because the dummies are part of X DataFrame
    data = pd.concat([data, dummies], axis=1)
    data.drop([variable], axis=1, inplace=True)

In [75]:
data.head()

Pclass       Age     SibSp     Parch      Fare  Sex_female  \
PassengerId                                                                 
1            0.827377 -0.592481  0.432793 -0.473674 -0.502445           0   
2           -1.566107  0.638789  0.432793 -0.473674  0.786845           1   
3            0.827377 -0.284663 -0.474545 -0.473674 -0.488854           1   
4           -1.566107  0.407926  0.432793 -0.473674  0.420730           1   
5            0.827377  0.407926 -0.474545 -0.473674 -0.486337           0   

             Sex_male  Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  \
PassengerId                                                                   
1                   1        0        0        0        0        0        0   
2                   0        0        0        1        0        0        0   
3                   0        0        0        0        0        0        0   
4                   0        0        0        1        0        0        0   
5                   1        0        0        0        0        0        0   

             Cabin_G  Cabin_None  Cabin_T  Embarked_C  Embarked_Missing  \
PassengerId                                                               
1                  0           1        0           0                 0   
2                  0           0        0           1                 0   
3                  0           1        0           0                 0   
4                  0           0        0           0                 0   
5                  0           1        0           0                 0   

             Embarked_Q  Embarked_S  
PassengerId                          
1                     0           1  
2                     0           0  
3                     0           1  
4                     0           1  
5                     0           1

In [76]:
categorical_variables = ['Sex', 'Cabin', 'Embarked']

for variable in categorical_variables:
    # Fill missing data with the word "Missing"
    data_test[variable].fillna("Missing", inplace=True)
    # Create array of dummies
    dummies = pd.get_dummies(data_test[variable], prefix=variable)
    # Update X to include dummies and drop the main variable
    # here I think axis=1 for pd.concat because the dummies are part of X DataFrame
    data_test = pd.concat([data_test, dummies], axis=1)
    data_test.drop([variable], axis=1, inplace=True)

In [77]:
data_test.head()

Pclass       Age     SibSp     Parch      Fare  Sex_female  \
PassengerId                                                                 
892          0.827377  0.369449 -0.474545 -0.473674 -0.490783           0   
893          0.827377  1.331378  0.432793 -0.473674 -0.507479           1   
894         -0.369365  2.485693 -0.474545 -0.473674 -0.453367           0   
895          0.827377 -0.207709 -0.474545 -0.473674 -0.474005           0   
896          0.827377 -0.592481  0.432793  0.767630 -0.401017           1   

             Sex_male  Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  \
PassengerId                                                                   
892                 1        0        0        0        0        0        0   
893                 0        0        0        0        0        0        0   
894                 1        0        0        0        0        0        0   
895                 1        0        0        0        0        0        0   
896                 0        0        0        0        0        0        0   

             Cabin_G  Cabin_None  Embarked_C  Embarked_Q  Embarked_S  
PassengerId                                                           
892                0           1           0           1           0  
893                0           1           0           0           1  
894                0           1           0           1           0  
895                0           1           0           0           1  
896                0           1           0           0           1

In [78]:
data.drop(["Cabin_T", "Embarked_Missing"], axis=1, inplace=True)

In [79]:
data.head()

Pclass       Age     SibSp     Parch      Fare  Sex_female  \
PassengerId                                                                 
1            0.827377 -0.592481  0.432793 -0.473674 -0.502445           0   
2           -1.566107  0.638789  0.432793 -0.473674  0.786845           1   
3            0.827377 -0.284663 -0.474545 -0.473674 -0.488854           1   
4           -1.566107  0.407926  0.432793 -0.473674  0.420730           1   
5            0.827377  0.407926 -0.474545 -0.473674 -0.486337           0   

             Sex_male  Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  \
PassengerId                                                                   
1                   1        0        0        0        0        0        0   
2                   0        0        0        1        0        0        0   
3                   0        0        0        0        0        0        0   
4                   0        0        0        1        0        0        0   
5                   1        0        0        0        0        0        0   

             Cabin_G  Cabin_None  Embarked_C  Embarked_Q  Embarked_S  
PassengerId                                                           
1                  0           1           0           0           1  
2                  0           0           1           0           0  
3                  0           1           0           0           1  
4                  0           0           0           0           1  
5                  0           1           0           0           1

In [80]:
print(data.shape)
print(data_test.shape)

(891, 18)
(418, 18)


### The above drop step was done to make sure the training set and test set have the same number of columns

In [189]:
rf = RandomForestClassifier(n_estimators=1000, n_jobs=-1, random_state=42, max_features="auto", min_samples_leaf=5)

rf.fit(data, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [190]:
cross_val_score(rf, data, y, cv=10, scoring="accuracy")

array([ 0.8       ,  0.8       ,  0.76404494,  0.86516854,  0.8988764 ,
        0.83146067,  0.83146067,  0.78651685,  0.86516854,  0.84090909])

In [191]:
training_pred = rf.predict(data)

from sklearn.metrics import accuracy_score
acc = accuracy_score(y, training_pred)

In [192]:
print("Random Forest accuracy score: ", acc)

Random Forest accuracy score:  0.864197530864


### Trying out Support Vector Machine

In [120]:
from sklearn.svm import SVC

svm_clf = SVC(C=1000, random_state=0)

In [121]:
svm_clf.fit(data, y)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [122]:
cross_val_score(svm_clf, data, y, cv=10, scoring="accuracy")

array([ 0.76666667,  0.76666667,  0.75280899,  0.82022472,  0.85393258,
        0.78651685,  0.78651685,  0.75280899,  0.85393258,  0.85227273])

In [123]:
svm_clf_preds = svm_clf.predict(data)

from sklearn.metrics import accuracy_score
svm_acc = accuracy_score(y, svm_clf_preds)

In [124]:
print("SVM accuracy score: ", svm_acc)

SVM accuracy score:  0.890011223345


In [125]:
svm_preds = svm_clf.predict(data_test)

In [126]:
my_titanic_submission = pd.DataFrame({'PassengerId': data_test.index, 'Survived': svm_preds})

my_titanic_submission.to_csv('Titanic_submission9_svm.csv', index=False)

### Gradient Boosted Regression Tree

In [178]:
from sklearn.ensemble import GradientBoostingClassifier

gbrt_clf = GradientBoostingClassifier(random_state=0, max_depth=3)
gbrt_clf.fit(data, y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=0, subsample=1.0, verbose=0,
              warm_start=False)

In [179]:
cross_val_score(gbrt_clf, data, y, cv=10, scoring="accuracy")

array([ 0.8       ,  0.8       ,  0.75280899,  0.84269663,  0.8988764 ,
        0.83146067,  0.82022472,  0.7752809 ,  0.86516854,  0.84090909])

In [180]:
gbrt_clf_preds = gbrt_clf.predict(data)

from sklearn.metrics import accuracy_score
gbrt_acc = accuracy_score(y, gbrt_clf_preds)

print("Accuracy of gbrt training set: ", gbrt_acc)

Accuracy of gbrt training set:  0.887766554433


In [181]:
gbrt_preds = gbrt_clf.predict(data_test)

In [182]:
my_titanic_submission = pd.DataFrame({'PassengerId': data_test.index, 'Survived': gbrt_preds})

my_titanic_submission.to_csv('Titanic_submission10_gbrt.csv', index=False)

### Multilayer Perceptron

In [161]:
from sklearn.neural_network import MLPClassifier

mlp_clf = MLPClassifier(max_iter=1000, alpha=0.001, random_state=0)
mlp_clf.fit(data, y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=0, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [162]:
cross_val_score(mlp_clf, data, y, cv=10, scoring="accuracy")

array([ 0.83333333,  0.77777778,  0.7752809 ,  0.87640449,  0.82022472,
        0.78651685,  0.79775281,  0.82022472,  0.84269663,  0.84090909])

In [163]:
mlp_clf_preds = mlp_clf.predict(data)

from sklearn.metrics import accuracy_score
mlp_acc = accuracy_score(y, mlp_clf_preds)

print("Accuracy of mlp training set: ", mlp_acc)

Accuracy of mlp training set:  0.864197530864


In [144]:
mlp_preds = mlp_clf.predict(data_test)

In [145]:
my_titanic_submission = pd.DataFrame({'PassengerId': data_test.index, 'Survived': mlp_preds})

my_titanic_submission.to_csv('Titanic_submission11_mlp.csv', index=False)

In [187]:
rf_preds = rf.predict(data_test)

In [188]:
my_titanic_submission = pd.DataFrame({'PassengerId': data_test.index, 'Survived': rf_preds})

my_titanic_submission.to_csv('Titanic_submission12_rf.csv', index=False)

In [104]:
svm_preds = svm_clf.predict(data_test)

In [105]:
my_titanic_submission = pd.DataFrame({'PassengerId': data_test.index, 'Survived': svm_preds})

my_titanic_submission.to_csv('Titanic_submission6.csv', index=False)

In [106]:
svm_preds

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0,

In [107]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()
knn_clf.fit(data, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [108]:
cross_val_score(knn_clf, data, y, cv=10, scoring="accuracy")

array([ 0.78888889,  0.81111111,  0.7752809 ,  0.78651685,  0.86516854,
        0.78651685,  0.85393258,  0.78651685,  0.84269663,  0.77272727])

In [109]:
knn_clf_preds = knn_clf.predict(data)

from sklearn.metrics import accuracy_score
knn_acc = accuracy_score(y, knn_clf_preds)

print("knn accuracy score: ", knn_acc)

knn accuracy score:  0.854096520763


In [110]:
knn_preds = knn_clf.predict(data_test) 

In [111]:
my_titanic_submission = pd.DataFrame({'PassengerId': data_test.index, 'Survived': knn_preds})

my_titanic_submission.to_csv('Titanic_submission8_knn.csv', index=False)

In [112]:
knn_preds

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

### Now I want to do it over again using scaled numerical variables within the *data* DataFrame

### Something I also forgot to do was shuffle the training set.  Shuffling will guarantee that all cross-validation folds will be similar.  Moreover, some learning algorithms are sensitive to the order of the training instances, and they perform poorly if they get many similar instances in a row.

In [349]:
# For example

#import numpy as np

#shuffle_index = np.random.permutation(60000)
#X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]


### Trying out Confusion Matrix

In [223]:
from sklearn.model_selection import cross_val_predict

y_pred = cross_val_predict(rf, data, y, cv=10)

In [224]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y, y_pred)

array([[504,  45],
       [108, 234]])

In [225]:
from sklearn.metrics import precision_score, recall_score

In [226]:
precision_score(y, y_pred)

0.8387096774193549

In [227]:
recall_score(y, y_pred)

0.6842105263157895

In [228]:
from sklearn.metrics import f1_score

In [229]:
f1_score(y, y_pred)

0.7536231884057972